"""
knowledge.py
============
All of Sulitha's profile info as plain text chunks for RAG indexing.

HOW TO UPDATE:
- Edit any string below to keep the agent accurate
- Add new DOCUMENTS entries for new projects, jobs, awards
- Redeploy the HF Space — FAISS rebuilds at startup automatically
"""

DOCUMENTS = [

# ── PROFILE ──────────────────────────────────────────────────────────────────
"""
PROFILE
My name is Sulitha Nulaksha Bandara. I am a third-year Computer Engineering
undergraduate at the University of Ruhuna, Sri Lanka, with a current GPA of
3.92 out of 4.00.
I specialise in AI-powered systems: intelligent virtual agents, multi-agent
decision architectures, computer vision-based interaction, and immersive AI
environments. I am passionate about agentic AI, LLM applications, and building
systems that integrate real-time perception, reasoning, and automation.
I combine AI engineering depth with immersive systems experience across Unity
and Unreal Engine. I am currently advancing my expertise in agentic AI frameworks
including LangGraph, CrewAI, AutoGen, OpenAI Agents SDK, and MCP.
""",

# ── CONTACT ──────────────────────────────────────────────────────────────────
"""
CONTACT INFORMATION
Email: nulakshastudy19@gmail.com
Phone: +94 714 262 972
LinkedIn: https://linkedin.com/in/nulaksha-bandara
GitHub: https://github.com/UGSNBandara
Portfolio website: https://sulitha-nulaksha-portfolio.vercel.app
Location: Sri Lanka
The best way to reach me is via email or LinkedIn.
""",

# ── EDUCATION ────────────────────────────────────────────────────────────────
"""
EDUCATION
I am studying for a B.Sc.Eng. (Hons) in Computer Engineering at the
University of Ruhuna, Sri Lanka, in the Department of Electrical and
Information Engineering. I started in 2022 and am currently in my third year.
My GPA is 3.92 out of 4.00.
""",

# ── AVAILABILITY ─────────────────────────────────────────────────────────────
"""
AVAILABILITY AND WHAT I AM LOOKING FOR
I am currently actively seeking internship opportunities in AI engineering,
machine learning, and related fields. I am open to remote and on-site positions.
I am particularly interested in roles involving agentic AI, LLM applications,
computer vision, and AI-powered product development.
If you are a recruiter or company interested in working with me, please reach
out via email at nulakshastudy19@gmail.com or LinkedIn.
""",

# ── PROJECT: SOFIA ────────────────────────────────────────────────────────────
"""
PROJECT: SOFIA — 3D Intelligent Virtual AI Agent (2025)
Sofia is my most advanced project. She is a 3D animated AI agent deployable
through both a React and TypeScript web interface and a Unity-based AR application.
She is a fully multi-agent system built on Google ADK (Agent Development Kit),
delivering real-time lip-synced responses generated by Gemini with Microsoft Azure
STT and TTS for voice interaction.
A dedicated computer vision module continuously analyses the person she is speaking
with — estimating gender, approximate age, and emotional state — while live weather
API data adds environmental context for personalisation.
Sofia was designed as a customer assistant for an ice cream shop. She recommends
products via real-time customer clustering, logs emotion and satisfaction data to
MongoDB throughout each interaction, and surfaces aggregated insights on a manager
dashboard to support data-driven service decisions. SQLite handles fast in-agent
state retrieval. A custom model I trained is hosted on Hugging Face.
Sofia was exhibited at ReXtro 2025 at the Faculty of Engineering, University of
Ruhuna, in December 2025.
Tech stack: React, TypeScript, FastAPI, Google ADK, Gemini API, Microsoft Azure
STT/TTS, MongoDB, SQLite, Unity (AR), Hugging Face, Railway.
""",

# ── PROJECT: MOTIONX ─────────────────────────────────────────────────────────
"""
PROJECT: MOTIONX — Motion and Voice Controlled Original Game Series (2025)
MotionX is a series of three original games I built, each controlled entirely
through player body movement and/or voice via a real-time computer vision and
speech detection pipeline. There is no keyboard or mouse — the player's body
is the controller.

LumRun: An endless runner set in a cemetery, controlled by the player running
in place. The character moves as the player moves.

Music Bubble Runner: The player runs to intercept musical bubbles mid-air,
generating a live reactive soundtrack from their movement.

CWL (Charms and Wands League): A Harry Potter-inspired game where the in-game
wand syncs in real time with the player's physical wand hand movements. A voice
detection system identifies the charm the player speaks aloud — such as
Expelliarmus or Lumos — and triggers the corresponding in-game effect.

All three games and Sofia were exhibited at ReXtro 2025 at the Faculty of
Engineering, University of Ruhuna, in December 2025.
Tech stack: Computer Vision, Speech Detection, Python.
""",

# ── PROJECT: GROCERIA ────────────────────────────────────────────────────────
"""
PROJECT: GROCERIA — Multi-Agent Smart Shopping Planning System (2025)
Groceria is a cooperative multi-agent system that generates optimised grocery
shopping plans. Agents scrape vendor product pages in real time, with an
automatically self-updating product database that refreshes data only after a
configurable expiry window.
The planning pipeline reasons jointly over user preferences, product availability,
delivery costs, and budget constraints. It automatically applies credit card-
specific discounts when computing the most cost-effective plan from a given
product list.
Groceria was a finalist in the SLAIC AI Challenge 2025.
Tech stack: Next.js, FastAPI, Google ADK, real-time web scraper, auto-updating
product database.
""",

# ── PROJECT: QUICKREF ────────────────────────────────────────────────────────
"""
PROJECT: QUICKREF — AI Document Question Answering System (2025)
QuickRef is an end-to-end RAG system that extracts knowledge from PDFs and web
pages and answers natural language queries using semantic search and large language
models. Text is chunked using RecursiveCharacterTextSplitter, indexed in FAISS
using NVIDIA BGE-M3 embeddings, and answered by Falcon-7B-Instruct through
RetrievalQAWithSourcesChain with source citations.
Tech stack: Python, LangChain, FAISS, NVIDIA BGE-M3, Falcon-7B-Instruct,
Streamlit, PyPDFLoader, UnstructuredURLLoader.
""",

# ── PROJECT: ANOOTE ──────────────────────────────────────────────────────────
"""
PROJECT: ANOOTE — Anonymous Messaging Platform with NLP Harm Detection (2024)
AnoNote is an anonymous messaging platform where users share a unique link to
receive messages without revealing the sender's identity. It integrates a
multilingual NLP harm detection pipeline covering English, Sinhala, and Singlish.
The system uses four TF-IDF models: one for English, one for Sinhala, one for
Singlish, and one English-Singlish classifier, plus a custom SpaCy pipeline for
predefined harmful term detection. All models are hosted on Hugging Face and
FastAPI handles inference.
Tech stack: React.js, Node.js, Express.js, MongoDB, FastAPI, TF-IDF, SpaCy,
Hugging Face.
""",

# ── PROJECT: CROP DISEASE ────────────────────────────────────────────────────
"""
PROJECT: CROP DISEASE DETECTION SYSTEM (2024)
A deep learning system with three CNN models trained using TensorFlow:
Bell Pepper Disease Prediction — identifies and diagnoses diseases in bell
pepper leaves. Potato Disease Prediction — detects various potato leaf diseases.
Crop Classifier — distinguishes between potato and bell pepper leaves to route
images to the correct disease model.
The React.js frontend handles image upload and displays predictions, actionable
tips, and fertiliser recommendations. The FastAPI backend processes images and
returns results.
Tech stack: React.js, FastAPI, TensorFlow, Python, CNN, Deep Learning.
""",

# ── RESEARCH ─────────────────────────────────────────────────────────────────
"""
RESEARCH PROJECTS

Physics-Aware Generative AI for EMI Prediction in PCB Layouts (2026):
I am part of a team investigating physics-informed generative models for
predicting electromagnetic interference patterns in printed circuit board layouts.
Our team was shortlisted in the IEEE IES Generative AI Challenge 2026 out of
575 submissions from 57 countries.

Intelligent Virtual Agents in Immersive Environments (2025, ongoing):
I am advancing Sofia-style agents toward fully autonomous, context-aware
interaction in immersive 3D and AR environments, integrating LLM reasoning,
computer vision perception, and simulation platforms like Unreal Engine and Unity.

Clean Scene Reconstruction for VR/AR using Gaussian Splatting (2025, ongoing):
I am building a pre-processing pipeline to detect and remove moving objects,
vehicles, humans, and privacy-sensitive data from recorded video before 3D
reconstruction, improving the quality of Gaussian splatting outputs for VR/AR
and game environments.
""",

# ── SKILLS ───────────────────────────────────────────────────────────────────
"""
TECHNICAL SKILLS
Programming Languages: Python, JavaScript, TypeScript, C++, C#
AI and ML: Machine Learning, Deep Learning (CNN), Computer Vision, NLP,
  Multi-Agent Systems, LLM Applications, Agentic AI
Agent Frameworks: Google ADK, LangChain, LangGraph, CrewAI, AutoGen,
  OpenAI Agents SDK, MCP (Model Context Protocol)
AI Tooling: Prompt Engineering, RAG, Vector Embeddings (FAISS, BGE-M3),
  Semantic Search, Hugging Face
Backends and APIs: FastAPI, Node.js, Express.js, REST APIs, Gemini API,
  Microsoft Azure STT/TTS, OpenAI API, Weather APIs
Frontend: React.js, TypeScript, Next.js, Streamlit
Databases: MongoDB, SQLite
Cloud and DevOps: AWS EC2 (app hosting, CI/CD pipeline, ML training),
  Docker, Git, Linux
Immersive Development: Unity Engine, Unreal Engine, AR Development
ML Frameworks: TensorFlow, PyTorch, SpaCy, scikit-learn
""",

# ── AWARDS ───────────────────────────────────────────────────────────────────
"""
AWARDS AND RECOGNITION
- Shortlisted Team — IEEE IES Generative AI Challenge 2026
  (575 submissions from 57 countries)
- Top 50 Rising Founders — Neo Ventures National Innovation Accelerator Programme (2025)
- 1st Runner-Up — Code Night 2025, University of Ruhuna
- 1st Runner-Up — Red Cypher 2.0 Capture-the-Flag Competition (2025)
- Finalist — CodeX and CyberRush, CodeJam Series, University of Moratuwa (2025)
- Outstanding Volunteer of the Month — IEEE Student Branch, University of Ruhuna (2024)
""",

# ── LEADERSHIP ───────────────────────────────────────────────────────────────
"""
LEADERSHIP AND PROFESSIONAL EXPERIENCE
Program Team Lead — HaXtreme 3.0, IEEE Student Branch, University of Ruhuna (2024):
Led planning and full execution of a faculty-level competitive programming event.
Managed logistics, timeline, and cross-departmental participant communication.

Technical Team Member — HaXtreme 4.0, IEEE Student Branch (2025):
Contributed to technical challenge design and on-ground execution of a
university-level hackathon.

Program Team Member — Eminence 5.0 and VoltCast 1.0, IEEE Student Branch (2025):
Organised a faculty-level professional development event series and a renewable
energy ideathon with an accompanying webinar series.
""",

]
